version: '1.0'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: vnsh
      POSTGRES_PASSWORD: password
      POSTGRES_DB: momentum
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data

volumes:
  postgres-data:
  neo4j-data: